# Generated by Django 5.2.5 on 2025-12-16 08:47

import hospital.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(blank=True, null=True, storage=hospital.storage_backends.MediaStorage(), upload_to='profile/'),
        ),
    ]
