# Generated by Django 5.2.6 on 2025-10-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_labresult_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='vital_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitals_entries', to='hospital.vitalrequest'),
        ),
    ]
