# Generated by Django 5.2.5 on 2025-11-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_vitals_vital_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='enable_toc',
            field=models.BooleanField(default=True, help_text='Enable table of contents for this post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated table of contents'),
        ),
    ]
