# Generated by Django 5.2.5 on 2025-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_blogpost_enable_toc_blogpost_table_of_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Second image for the post', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Third image for the post', null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subheadings',
            field=models.JSONField(blank=True, default=list, help_text='Structured subheadings with descriptions'),
        ),
    ]
