# Generated by Django 5.2.5 on 2025-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_blogpost_image_1_blogpost_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='enable_toc',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheadings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
